using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace Demo_1__OOP
{
    internal struct Point
    {
        //Attributes
        public int x; 
        public int y;
        //Constructor =>Is special Function
        //has the same name as ClassInterfaceAttribute or struct
        //has no return
        public Point()//parameterless constructor //generated by default even if not written here
        {
         //intialize variables   
         x= 0;  
         y= 0;
        }
        public Point(int _x,int _y)
        {
            x=_x;
            y=_y;
        }
        public override string ToString()
        {
            return $"The X is:{x} The Y is: {y}";
        }
    }
}
